config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  root "peliculas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :peliculas do
    resources :funcions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  validates_with FuncionValidator
  belongs_to :pelicula
  has_many :reservas

end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  has_many :funcions, dependent: :destroy

  validates :nombre, presence: true
  validates :sinopsis, presence: true
  validates :urlimagen, presence: true
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :funcion

  validates :persona, presence: true
  validates :celular, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funcions_controller.rb
class FuncionsController < ApplicationController
  def create
    @pelicula = Pelicula.find(params[:pelicula_id])
    @funcion = @pelicula.funcions.new(funcion_params)
    @funcion.cupos = 10
    if @funcion.save
      flash[:success] = "Función guardada correctamente"
    else
      flash[:error] = @funcion.errors.full_messages.join("\n")
    end
    redirect_to pelicula_path(@pelicula)
  end

  def destroy
    @pelicula = Pelicula.find(params[:pelicula_id])
    @funcion = @pelicula.funcions.find(params[:id])
    @funcion.destroy
    redirect_to pelicula_path(@article)
  end

  private
  def funcion_params
    params.require(:funcion).permit(:dia, :cupos)
  end
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  def index
    @peliculas = Pelicula.all
  end

  def show
    @pelicula = Pelicula.find(params[:id])
  end

  def new
    @pelicula = Pelicula.new
  end

  def create
    @pelicula = Pelicula.new(pelicula_params)
    if @pelicula.save
      redirect_to @pelicula
    else
      render :new
    end
  end

  def edit
    @pelicula = Pelicula.find(params[:id])
  end

  def update
    @pelicula = Pelicula.find(params[:id])

    if @pelicula.update(pelicula_params)
      redirect_to @pelicula
    else
      render :edit
    end
  end

  def destroy
    @pelicula= Pelicula.find(params[:id])
    @pelicula.destroy

    redirect_to rooth_path
  end

  private

  def pelicula_params
    params.require(:pelicula).permit(:nombre, :sinopsis, :urlimagen)
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  def index
    @reservas = Reserva.all
  end

  def show
    @reserva = Reserva.find(params[:id])
  end

  def new
    @reserva = Reserva.new
  end

  def create
    @reserva = Reserva.new(reserva_params)
    funcion = @reserva.funcion
    if @reserva.save
      funcion.cupos = funcion.cupos - 1
      funcion.save
      redirect_to @reserva
    else
      puts @reserva.errors.first.full_message
      render :new
    end
  end

  def edit
    @reserva = Reserva.find(params[:id])
  end

  def update
    @reserva = Reserva.find(params[:id])

    if @reserva.update(reserva_params)
      redirect_to @reserva
    else
      render :edit
    end
  end

  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    redirect_to reservas_path
  end

  private

  def reserva_params
    params.require(:reserva).permit(:persona, :correo, :cedula, :celular, :funcion_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcions_helper.rb
module FuncionsHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/funcions/_form.html.erb
<%= form_with model: [ @pelicula, @pelicula.funcions.build ] do |form| %>
  <p>
    <%= form.label :dia %><br>
    <%= form.date_field :dia %>
  </p>

    <%= flash[:error] %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/funcions/_funcion.html.erb
<p>
  <strong>Dia:</strong>
  <%= funcion.dia.strftime("%A, %d-%b-%Y") %>
</p>

<p>
  <strong>Cupos:</strong>
  <%= funcion.cupos %>
</p>

<p>
  <%= link_to 'Destruir Función', [funcion.pelicula, funcion],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
  <%= yield(:head) %>
  <title>Place it!</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'peliculas/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/views/peliculas/_form.html.erb
<%= form_with model: pelicula do |form| %>
  <div>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
    <% pelicula.errors.full_messages_for(:nombre).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :sinopsis %><br>
    <%= form.text_area :sinopsis %><br>
    <% pelicula.errors.full_messages_for(:sinopsis).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :urlimagen %><br>
    <%= form.text_field :urlimagen %><br>
    <% pelicula.errors.full_messages_for(:urlimagen).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/peliculas/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "<b>Place</b>it".html_safe, root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "<i class='bi bi-calendar'></i> Reservas".html_safe, reservas_path, class: "nav-link active", 'aria-current' => "page" %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='bi bi-film'></i> Peliculas".html_safe, root_path, class: "nav-link active", 'aria-current' => "page" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/peliculas/edit.html.erb
<h1>Editar Pelicula</h1>

<%= render "form", pelicula: @pelicula %>

app/views/peliculas/index.html.erb
<% content_for :head do %>
<style>
    .contenedor {
        position: relative;
        width: 100%;
    }

    .image {
        opacity: 1;
        display: block;
        width: 100%;
        height: auto;
        transition: .5s ease;
        backface-visibility: hidden;
    }

    .middle {
        transition: .5s ease;
        opacity: 0;
        position: absolute;
        top: 90%;
        left: 50%;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        text-align: center;
    }

    .contenedor:hover .image {
        opacity: 0.3;
    }

    .contenedor:hover .middle {
        opacity: 1;
    }

    .text {
        background-color: blue;
        color: white;
        font-size: 16px;
        padding: 16px 32px;
    }
</style>
  <% end %>

<h1>Peliculas</h1>

<%= link_to "<i class='bi bi-plus'></i> Crear nueva pelicula".html_safe, new_pelicula_path %>

<div class="container">
  <div class="row">
    <% @peliculas.each do |pelicula| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <div class="contenedor">
            <%= link_to image_tag(pelicula.urlimagen, alt: pelicula.nombre, class: "border border-light border-4", style: "width:100%"), pelicula %>
            <div class="middle">
              <%= link_to "Reserva", new_reserva_path(pelicula_id: pelicula.id), class: "btn btn-primary text" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/peliculas/new.html.erb
<h1>Nueva Pelicula</h1>

<%= render "form", pelicula: @pelicula %>

app/views/peliculas/show.html.erb
<h1><%= @pelicula.nombre %></h1>
<p><%= @pelicula.sinopsis %></p>

<% if true %>
  <%= image_tag(@pelicula.urlimagen, size: "160x220", alt: @pelicula.nombre) %>
<% end %>


<ul>
  <li><%= link_to "Editar", edit_pelicula_path(@pelicula) %></li>
  <li><%= link_to "Destroy", pelicula_path(@pelicula),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Funciones</h2>
<%= render @pelicula.funcions %>


<h2>Agregar funciones:</h2>
<%= render 'funcions/form' %>

app/views/reservas/_form.html.erb
<%= form_with model: reserva do |form| %>
  <div>
    <%= form.label :persona %><br>
    <%= form.text_field :persona %>
    <% @reserva.errors.full_messages_for(:persona).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :correo %><br>
    <%= form.text_field :correo %>
    <% @reserva.errors.full_messages_for(:correo).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :cedula %><br>
    <%= form.text_field :cedula %>
    <% @reserva.errors.full_messages_for(:cedula).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :celular %><br>
    <%= form.text_field :celular %>
    <% @reserva.errors.full_messages_for(:celular).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <% funciones = Funcion.where(pelicula_id: params[:pelicula_id]).collect {|fun| [fun.dia.strftime("%A, %d-%b-%Y"),fun.id]}  %>

    <%= form.label :funcion_id, "Función" %><br>
    <%= form.select :funcion_id, funciones %>

    <% @reserva.errors.full_messages_for(:funcion_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editar Reserva</h1>

<%= render "form", reserva: @reserva %>

app/views/reservas/index.html.erb
<h1>Reservas</h1>

<%= link_to "Nueva Reserva", new_reserva_path %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Pelicula</th>
    <th scope="col">Nombre reservante</th>
    <th scope="col">Correo electrónico</th>
    <th scope="col">Cedula</th>
    <th scope="col">Celular</th>
  </tr>
  </thead>
  <tbody>

  <% @reservas.each do |reserva| %>
    <tr>
      <td><%=  Pelicula.find(Funcion.find(reserva.funcion_id).pelicula_id).nombre %></td>
      <td><%= link_to reserva.persona, reserva %></td>
      <td><%= reserva.correo %></td>
      <td><%= reserva.cedula %></td>
      <td><%= reserva.celular %></td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/reservas/new.html.erb
<h1>Nueva Reserva</h1>

<%= render "form", reserva: @reserva %>

app/views/reservas/show.html.erb
<h1><%= @reserva.persona %></h1>

<p><%= Pelicula.find(Funcion.find(@reserva.funcion_id).pelicula_id).nombre %></p>
<p><%= Funcion.find(@reserva.funcion_id).dia.strftime("%A, %d-%b-%Y")
%></p>
<p><%= @reserva.correo %></p>
<p><%= @reserva.cedula %></p>
<p><%= @reserva.celular %></p>

<ul>
  <li><%= link_to "Editar", edit_reserva_path(@reserva) %></li>
  <li><%= link_to "Destroy", reserva_path(@reserva),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>

</ul>